# ============================================================
#  Academia - application.properties
#  Para alternar entre ambientes, ajuste o spring.profiles.active
# ============================================================

# Perfil ativo  (mysql | sqlserver)
spring.profiles.active=mysql

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
